[package]
name = "vpnutils"
version = "0.1.0"
authors = ["Giacomo Bagnoli <gbagnoli@gmail.com>"]
edition = "2018"

[dependencies]
diesel =         { version = "*", default-features = false, features = ["sqlite"] }
dotenv = "0.15.0"
