[package]
name = "vpnutils"
version = "0.1.0"
authors = ["Giacomo Bagnoli <gbagnoli@gmail.com>"]
edition = "2018"

[dependencies]
diesel = { version = "1.4.4", features = ["postgres"] }
dotenv = "0.15.0"
